### ISSUE TITLE
Downloads Same Song for certain countries(US)

### ISSUE THREAD

**Issue by DreadMcLaren** [ExtendLord/DeezLoader-Reborn#1]
Regardless what I download, it always downloads "David Guetta - Dirty Sexy".

This happens with both .mp3 and .flac files.

https://imgur.com/a/5wYHY
https://imgur.com/a/jHl8H

**Comment by ExtendLord** [comment]
What is your operating system and arch?<br/>
Where are from?<br/>
It is probably a bug with Deezer and not the software.<br/>
Someone else tried both this software and another software(Deezloadr) and it downloaded him the same song("Mad man").<br/>

**Comment by DreadMcLaren** [comment]
What is your operating system and arch?

Windows 10 x64

Where are from?

USA

Possible to implement a fix to eliminate using a VPN?

**Comment by ExtendLord** [comment]
@DreadMcLaren I apologize but I have no clue why some people from USA have the same problem.
I can't really do anything about this.
http://www.deezer.com/us/track/412536982
What do you see when you try to go to this track?

**Comment by DreadMcLaren** [comment]
@ExtendLord This is what I see when I click the link you provided:

https://imgur.com/a/32aTX

**Comment by ExtendLord** [comment]
@DreadMcLaren Fortunately for you, I have debugged the software and I'm fixing the US problem.

**Comment by cauavm15** [comment]
Why does my program close when I click to download some music?

**Comment by cauavm15** [comment]
Omg, I downloaded it again and it's right.

**Comment by LordZane** [comment]
Quick note, making a free account and adding your sid to the api file fixes this

**Comment by ExtendLord** [comment]
@LordZane I have a better idea

I will add an option for getting info though a proxy.

When the software gets the info of the track it does this through a proxy and then it downloads it normally without a proxy.

**Comment by manny729** [comment]
still not working for me im in usa try dl luis marte -the light and get this 1 - David Guetta - Dirty Sexy Money (feat. Charli XCX & French Montana) (GLOWINTHEDARK Remix)  im on windows 10 64 bit 

Version: 3.0.1

**Comment by ExtendLord** [comment]
@manny729 I did not fixed it yet

**Comment by manny729** [comment]
ok ill wait no rush thx

**Comment by ExtendLord** [comment]
@manny729 @LordZane @XplodingPancakes @DreadMcLaren Fixed the issue dfb3460ae0a83dd6981ab3d73db5eec08bc2a6f1

Now it will work for everybody but I need to just add the login window and 3.0.2 will be released.
