### ISSUE TITLE
Decoding failure at songs

### ISSUE THREAD

**Issue by syvhmx** [ExtendLord/DeezLoader-Reborn#10]
The song is "Joseph Vincent - Location", is 24-bit rather than 16-bit normally.
Don't know if it affects the song or album.
Error goes like this:  
`Decoding failure at 2:02.044 (Unsupported format or corrupted file)`
The encoding tool is also renamed to Lavf57.2.100 rather than libFLAC.

**Comment by ExtendLord** [comment]
@syvhmx 
First time I see a 24bit audio in Deezer.
Where did you saw that error?

**Comment by syvhmx** [comment]
Foobar2000.

**Comment by ExtendLord** [comment]
@syvhmx Maybe because the vendor I put for the tagger is libflac and there is no code that checks if its a libflac or Lavf

**Comment by syvhmx** [comment]
@ExtendLord Maybe, I don't know code really :sweat_smile:

**Comment by ExtendLord** [comment]
f50d175481f8e1233827b5c8eae066257e0555f7
@Uukrull Fixed this problem I think, if the problem still exists(You need clone the repository and compile it), reopen this issue.

**Comment by syvhmx** [comment]
@ExtendLord So far, no problems. Thanks too @Uukrull :+1:
