### ISSUE TITLE
Can't download anything... Downloads fail

### ISSUE THREAD

**Issue by geosabev** [ExtendLord/DeezLoader-Reborn#101]
I just don't know what happens... Every song or album I select either starts downloading and fails or it just fails at the beginning...

Any ideas what the reason might be?

**Comment by geosabev** [comment]
http://www.deezer.com/us/album/15458744
http://www.deezer.com/us/album/12395872

not only these.. i've been chosing different songs/albums just for test.. but nothing works

**Comment by ExtendLord** [comment]
@geosabev What is your version?

**Comment by geosabev** [comment]
3.0.3... the Windows x64 version...

**Comment by geosabev** [comment]
@ExtendLord I fixed it! I changed the download folder from C:\.... to D:\... and it worked out!
