### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by baptiste0928** [ExtendLord/DeezLoader-Reborn#102]
Hello,
I am a French Youtuber and I made a video on Deezloader.
I have no problem with the software but I have many comments from people who can not log in to their Deezer account. I think this problem comes from the 32 bit Windows version. 
Do you have a solution for this problem?

Regards,
Baptiste0928

PS: The link of my video: https://youtu.be/33lpg7Ou4gg

**Comment by Cris70** [comment]
Same problem here, and I'm using the 64bit version 3.03

**Comment by NicolasPL64** [comment]
I had the same problom and I had to put my email :/ 
Sry my english

**Comment by NicolasPL64** [comment]
It doesn't work with your username I think lelel

**Comment by Cris70** [comment]
Always used my email here (as v3.0.3 corrected the wording on the login screen) but cannot login nonetheless.

**Comment by NicolasPL64** [comment]
Hmm... change your pass? idk lol wait for the owner's answer

**Comment by NicolasPL64** [comment]
I had to change my pass like 3 times but then i put my email and it worked l0l

**Comment by Cris70** [comment]
Nah, why should I? My password works correctly on Deezer, so it should work on DeezLoader too.
I'll wait for @ExtendLord reply, but thank you anyway!

**Comment by NicolasPL64** [comment]
Okay! :D

**Comment by ExtendLord** [comment]
@Cris70 Can you please compile the project by these following steps and try again running with cmd?

1. Download Node JS 9.4.0
2. Download the zip file of the project in the link https://codeload.github.com/ExtendLord/DeezLoader-Reborn/zip/master
3. Extract the zip anywhere you want
4. Go to /app folder, edit deezer-api.js and replace the code inside with https://pastebin.com/raw/V5tsNvZD (Open the link and copy the code)
4. Run Compile.bat (As you are from windows)
5. After it finishes, go to dist/win-unpacked and run deezloader.exe using cmd
6. Try to login and see what the cmd returns.

**Comment by Cris70** [comment]
@ExtendLord will do it in the afternoon and I'll let you know.
Thank you!

**Comment by Cris70** [comment]
This is what I got:
```
D:\Prova\DeezLoader-Reborn-master\dist\win-unpacked>
Server is running @ localhost:1730
Settings Updated
==Login response==
Body:success_multi_account
Error:null
Code:200
```
It would seem a success message, isn't it? But the GUI says "incorrect email or password".
I hope you'll get something out of it.
If you need more tests don't hesitate to ask.

**Comment by ExtendLord** [comment]
@Cris70 @NicolasPL64 @baptiste0928  Oh that is because you have a family account.
https://github.com/ExtendLord/DeezLoader-Reborn/commit/2395a487e1307032d5c333d8d8ce783e3fa320a2
Fixed.

**Comment by Cris70** [comment]
Yay! Perfectly working now!!
Thank you!!

**Comment by 13mister37** [comment]
Sorry, doesn't work for me in 3.0.4. Have also an family subscription.

**Comment by ExtendLord** [comment]
@13mister37 I did not updated to 3.0.5 yet.
Meanwhile create a new account or compile the project by yourself and run it.

**Comment by 13mister37** [comment]
Ah, I understand. With 3.0.5 it will work? I'm so happy. 
Thank you for the good work and keep the work on!
