### ISSUE TITLE
[Feature Request] Save songs artworks as JPEG baseline

### ISSUE THREAD

**Issue by auanasgheps** [ExtendLord/DeezLoader-Reborn#103]
Hello
First of all a big **thank you** for keeping this project alive.

By defaults artworks that come from Deezer are saved in JPEG Progressive. This technology is great on the web, but comes with a price: almost no portable device (MP3/MP4 player) can show JPEG Progressive pictures. Potentially other programs/apps could have issues in opening JPEG Progressive artworks.
JPEG Baseline instead is the standard that can be read by any system. Would be great if artworks could be converted on the fly from progressive to baseline.

I don't really know how to implement this functionality, I'm just suggesting!

**Comment by ExtendLord** [comment]
I don't know what you are talking about.
Why would any program have issues with opening JPEG 😐?
The JPEG's are not different than the ones in Deezer app and every phone will show the covers.

**Comment by auanasgheps** [comment]
[Here](https://kb.tourwriter.com/baseline-jpeg-vs-progressive-jpeg) is explained what is the difference between JPEG baseline and progressive.
In my case my Sony portable player only reads JPEG baseline, like many other handheld devices. Android/iOS are probably are okay because are complex OSes.

However I just realised that this integration might not be easy: first we'll need to extract the artwork, then re-save it.

Nevermind, just close this request.

**Comment by ExtendLord** [comment]
I will just leave the image as it is without post processing
