### ISSUE TITLE
the app it closes when you add an album track playlist

### ISSUE THREAD

**Issue by fabriccioguzman** [ExtendLord/DeezLoader-Reborn#11]
it closes when you add an album track playlist that is or is not available or when a bug or error occurs does not give an error message it simply closes
I suggest that you make this app not close when an error occurs and try to eliminate the block by region of the music: http://www.deezer.com/en/playlist/2167349906

**Comment by ExtendLord** [comment]
@fabriccioguzman I'm on it.

**Comment by ExtendLord** [comment]
#5

**Comment by ExtendLord** [comment]
@fabriccioguzman 
d6dc6919616a8be743cb484a80099d85c6c5d459
Fixed
