### ISSUE TITLE
Unable to download songs blocked for region

### ISSUE THREAD

**Issue by D0ragn** [ExtendLord/DeezLoader-Reborn#12]
I've been trying to download some songs restricted by region, as "There Must Be More To Life Than This" from queen and michael jackson. Since this is not available in my country and some similar songs

**Comment by ExtendLord** [comment]
@D0ragn Then use a VPN, I have no other solution.

If it crashes when you try to you will have to compile the source by yourself untill I will release a new version.

486085129fd2c17eb72f55bfbef4555534b0479c

**Comment by D0ragn** [comment]
With or without a vpn I'm unable to download those songs

**Comment by ExtendLord** [comment]
@D0ragn That is because you chose a country that is blocked from downloading this specific song.
Where are you from and what is the location you chose for the VPN?

**Comment by D0ragn** [comment]
I'm from Peru, i'm trying to download from USA, UK, Astralia and Japan

**Comment by ExtendLord** [comment]
@D0ragn Can you download anything else?

**Comment by D0ragn** [comment]
I search a couple of albums that are not in my country and download without problems

**Comment by D0ragn** [comment]
i search those albums on google and choose the URL download option, because the program don't listed that albums, since they are not available in my country, i'm still using the vpn ion the release country of the albums

**Comment by ExtendLord** [comment]
@D0ragn How the software behaves when you try to download something that you are unable to?

**Comment by ExtendLord** [comment]
@D0ragn Well I can't play it by myself on Deezer so the problem is not related to the software.

**Comment by D0ragn** [comment]
The behave is normal, in the queen song the software show the download complete icon but in the download folder nothing.
When I dowloaded as full album the download is ok also, the song is skiped and the file folder show:
tracks 01, 02, 04 and missed the 03 that is the country blocked track.

In the case of the other albums blocked, they downloaded normally without any problem.

**Comment by D0ragn** [comment]
are you able  to listen these two songs?
these are blocked in my country:
http://www.deezer.com/es/track/88845365
http://www.deezer.com/es/track/5755830

**Comment by ExtendLord** [comment]
@D0ragn Nope

**Comment by ExtendLord** [comment]
@D0ragn the issue is closed due to not being a problem.

**Comment by ExtendLord** [comment]
Blocked songs cant be bypassed by any software.
And VPN can only bypass if the country is available
