### ISSUE TITLE
Trailing dot - addendum

### ISSUE THREAD

**Issue by GithubUser5462** [ExtendLord/DeezLoader-Reborn#13]
Hello, first of all thank you for maintaining and sharing this great software.

I noticed you made a patch for the trailing dot problem on windows.
I'd like to ask you to tweak the patch a little, since some albums have more than one dot at the end.
Worst case example there is even an album by "They've Shot Flanigan" titled just "...".

Changing the line 850 from:
`if(str[str.length-1] == "."){`
to
`while(str[str.length-1] == "."){`
should be enough imo.

**Comment by ExtendLord** [comment]
c516563edfdcf3036fa776ccbe4077b32bd47a82
Fixed
