### ISSUE TITLE
could you make a website for the application?

### ISSUE THREAD

**Issue by altntowin** [ExtendLord/DeezLoader-Reborn#14]
Hi i love deezloader , but  , would be good if you create a website for deezloader , it will be more friendly for the users
please

**Comment by mvusmvus** [comment]
The dev(s) should primarily concentrate on eradicating existing issues. Besides, the friendlier it's made for the users, the more widespread it gets. The more widespread it gets, the more attention it attracts. The more attention it attracts, the higher the chances of Deezer people patching the vulnerability.

**Comment by ExtendLord** [comment]
It will be a no for now @altntowin @mvusmvus .
