### ISSUE TITLE
Can't download song with / (forward slash) in the name.

### ISSUE THREAD

**Issue by deomkds** [ExtendLord/DeezLoader-Reborn#15]
If you try to download a song with a forward slash ( / ) in the name, Deezloader will report the download succeeded, but no file will be created on disk. The download folder will remain empty.

I noticed this while trying to download "TINFOIL / POWERLESS (Instrumental)" from _LIVING THINGS: Acapellas and Instrumentals_, an album by Linkin Park.

**Comment by mvusmvus** [comment]
Yep, same here.

**Comment by syvhmx** [comment]
Yup, Windows file formatting. It's built that way.  
If you try to name a folder or file, you cannot use these symbols:
`\ / : * ? " < > |`

The best way to do is to replace the above symbols for Windows OS (or Linux and macOS too if you want) to a dash (-) or a dot/period (.) Maybe that should fix it. @ExtendLord  

On second thought, maybe just removing any above symbols when creating a folder/file would be enough.  
Tags will still be unaffected.

**Comment by ExtendLord** [comment]
@syvhmx The name is filtered already so that is not the problem.
I will check it out soon

**Comment by deomkds** [comment]
I'm on macOS 10.13, sorry for not mentioning that.

I've also tried changing the _Track names_ option in Settings to something that doesn't include the actual track name, but that didn't work either. It still couldn't create the file.
![captura de tela 2018-01-15 as 20 51 43](https://user-images.githubusercontent.com/5448503/34964687-eacff536-fa35-11e7-9bfa-cf17c9d6299f.png)

**Comment by ExtendLord** [comment]
@deomkds @syvhmx @mvusmvus This song is not even playable in deezer its self so thats why the software did not downloaded it(Compiling the software), the 3.0.1 will crash.
Open the issue if anything else is needed.
