### ISSUE TITLE
Deezloader downloads CORRUPTED flac streams

### ISSUE THREAD

**Issue by mvusmvus** [ExtendLord/DeezLoader-Reborn#16]
I learned that some of the flac files DeezLoader downloads are corrupted, and re-downloading them does not help. Take [this release](https://www.deezer.com/album/1146141) for example. No matter how much times I download it, [tracks 1 and 3 always end up corrupted, which I learned by using "Verify Integrity" utility in foobar2000](https://i.imgur.com/qTBShBk.jpg). The reason I know that the files aren't corrupted on server is because when downloaded with SMLoader v1.3.0, [the files' integrity is uncorrupted](https://i.imgur.com/v8jGd8E.jpg). Through different proxies, I tested this on versions 2.3.1 and 3.0.1

**Comment by ExtendLord** [comment]
![default](https://user-images.githubusercontent.com/26222159/34928146-3f5200ee-f9c4-11e7-9d54-a6c6e56d1fc7.png)
@mvusmvus "Verify Integrity did not showed me a warning when I scanned a FLAC file.

**Comment by mvusmvus** [comment]
Try downloading this release
https://www.deezer.com/album/1146141

**Comment by ExtendLord** [comment]
@mvusmvus It could be because of the tags system.

**Comment by ExtendLord** [comment]
@mvusmvus For some reason "NYC" is identical with the one that I've downloaded using a plugin in tampermonkey and the other two are different.
So its probably not because of the tags.

**Comment by mvusmvus** [comment]
Probably not, no. What's funny is that only certain files end up corrupted.

Regardless, this is a pretty serious issue. Any idea how to fix it?

**Comment by ExtendLord** [comment]
@mvusmvus I will try to find out the reason behind it.
When I will have time

**Comment by mvusmvus** [comment]
That would be nice. From my perspective this matter is a #1 priority. I mean, the app is just downloading corrupted files.

**Comment by Uukrull** [comment]
I created a PR that fixes the problem: https://github.com/ExtendLord/DeezLoader-Reborn/pull/18

**Comment by ExtendLord** [comment]
@Uukrull Fixed the problem f50d175481f8e1233827b5c8eae066257e0555f7
Did a double check on the album you have tried and a couple of songs.
