### ISSUE TITLE
libFLAC difference

### ISSUE THREAD

**Issue by BNFCTR** [ExtendLord/DeezLoader-Reborn#19]
I've downloaded a few albums so far (using v3.0.1) but while looking at media infos of songs I've noticed that some songs' libFLAC versions are different than the others. Is it normal to be that way or is it some kind of bug or something?

**Comment by ExtendLord** [comment]
@Uukrull released a new patch f50d175481f8e1233827b5c8eae066257e0555f7 .
You can clone this repo(Downloading the zip) and run compile.bat/compile.sh to compile it and try out if the libFLAC version is still different in different songs.

**Comment by syvhmx** [comment]
libFLAC version is still different, but no problems. File integrity checked. All fine. Some have the same version, while some would use Lavf32.  

Does it affect songs if they differ?

**Comment by ExtendLord** [comment]
@syvhmx No.
I will still check about it but that would be the last thing now.
