### ISSUE TITLE
Some songs don't have genre tag (It never has)

### ISSUE THREAD

**Issue by syvhmx** [ExtendLord/DeezLoader-Reborn#20]
I've checked on songs, like:
`Maher Zain - One (album)`
According to their API, it never has a genre tag. Goes like this:
```
"genre_id": -1,
  "genres": {
    "data": [

    ]
  },
```
Is is better to leave as 'undefined' in the tag or remove it?

**Comment by ExtendLord** [comment]
c516563edfdcf3036fa776ccbe4077b32bd47a82
Fixed
