### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Jeffdow85** [ExtendLord/DeezLoader-Reborn#21]
Hey, is there any way to compile for android apk? or what files and port number can i use to run a node.js server with Servers Ultimate (android app) or similar regards jeff and thanks for keeping this project alive !

**Comment by ExtendLord** [comment]
I apologize but there is no support for android nor will be any time soon.

**Comment by Jeffdow85** [comment]
No worries thanks anyway working fine on windows for me :)
