### ISSUE TITLE
Always download EL BAÑO.

### ISSUE THREAD

**Issue by vishwarajsali** [ExtendLord/DeezLoader-Reborn#23]
Whenever I am trying to download songs always download EL BAÑO.

**Comment by aalireza439** [comment]
I have the same issue, can you tell how you solve this?

**Comment by ExtendLord** [comment]
@aalireza439bUse a VPN meanwhile untill I will solve this.

**Comment by jaredmfier** [comment]
SMLoadr fixed this, any chance you can implement? https://v.teknik.io/v/0CZbt
