### ISSUE TITLE
the application stops working when it tries to download more than download more than 65 songs

### ISSUE THREAD

**Issue by Jaime0657** [ExtendLord/DeezLoader-Reborn#25]

**Comment by ExtendLord** [comment]
@Jaime0657 Name of albums/playlists/tracks?

**Comment by Jaime0657** [comment]
http://www.deezer.com/playlist/3546133526?utm_source=deezer&utm_content=playlist-3546133526&utm_term=1639339566_1516064007&utm_medium=web 

I try using a vpn but still not working

**Comment by ExtendLord** [comment]
Fixed the issue dfb3460ae0a83dd6981ab3d73db5eec08bc2a6f1

But I need to just add the login window and 3.0.2 will be released.

**Comment by syvhmx** [comment]
Does this mean using a master account?  
If yes, then how would it cope to have >1000 IP's using it? Won't it be detected?  
If yes, another project did also the same, then changed it to use own account.
If no, then ignore this.

**Comment by ExtendLord** [comment]
@syvhmx lol nope.
> add the login window 
Login window, so you will enter your username and password(Or just create another one if you suspect that the info will be stolen)

**Comment by Jaime0657** [comment]
can i use my own account?
