### ISSUE TITLE
Track names for more than one disc

### ISSUE THREAD

**Issue by syvhmx** [ExtendLord/DeezLoader-Reborn#26]
The order is like this:  
```
if 'disknumber' = 1,
    filename = 'tracknumber' - 'title';
if 'disknumber' > 1,
    filename = 'disknumber' - 'tracknumber' - 'title'
```

This will prevent songs with 2 discs to be like this:
![afas](https://user-images.githubusercontent.com/33489835/34966533-1b1f6148-fa65-11e7-92d9-8568b6d36913.PNG)
.

or I can just turn on the 'Part of a set' column. :smile:

**Comment by ExtendLord** [comment]
I need to get the last track numbers of each disc and add it or create a disc 1 and disc 2

**Comment by ExtendLord** [comment]
a33ce6ec9fb07f0ed4cef560a7a6df4dfa4993b5 a8591b92dddd85c70ce02907050275a3851ea21e Fixed
Sorry for the huge delay.
