### ISSUE TITLE
Option to save artwork in a folder

### ISSUE THREAD

**Issue by mvusmvus** [ExtendLord/DeezLoader-Reborn#28]
Basically, this. An option to select resolution and name of artwork image that will be saved to album's folder.

**Comment by ExtendLord** [comment]
There is an option for resolution and it is saved in a temporary folder for artwork

**Comment by mvusmvus** [comment]
I feel as though I didn't make myself clear. What I meant is that the album artwork should be saved into the folder of a downloaded album. SMLoader does that automatically. but there's currently no such option in DeezLoader.
