### ISSUE TITLE
Tracks not downloading, creates empty folder

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#29]
Hi Extendlord

I am finding that some albums don't download, the UI doesn't say it failed, but the folder is empty. I have feeling that with HIFI enabled, some tracks are not uploaded as FLAC so don't download, but I could be completely wrong.

I will test with HIFI disabled and update this issue with more info.

K

**Comment by virtualviolet** [comment]
Ok, so yes confirmed. It seems that some artists/labels are only uploading 320k MP3's... Damn. With HIFI disabled the tracks download ok.

**Comment by virtualviolet** [comment]
Could you add a feature where with HIFI enabled, you have two columns for the download button/s, one button for MP3 and the other for FLAC? So when HIFI is enabled but FLAC is not available the FLAC button greyed out. Just remove the HIFI option and have two buttons, one for MP3 and the other for FLAC...

**Comment by ExtendLord** [comment]
Can you clone this repo(download the zip) and compile it?
Then run the deezloader you have just compiled and check if there is still an issue

**Comment by virtualviolet** [comment]
Yes, before I do, can I ask what you have changed? Was it not what I thought and something else?

**Comment by ExtendLord** [comment]
@virtualviolet You can check the commits after the 3.0.1 commit to see what is chaned.
I will release an update soon

**Comment by mvusmvus** [comment]
virtualviolet, which albums in particular do not download for you, could you provide a couple links?

**Comment by virtualviolet** [comment]
I am searching for them in the GUI, gave up trying to use a playlist, just bombed after 5 tracks. 
By doing it an album at a time and building spreadsheet as I go, I can manage/track the downloads, if it bombs I know where I was up to... really need to save the download list in the user home dir for persistence ;-)

Guys, PM me and I will provide some details.

Also, tried to compile on Mac OS Sierra via home-brew/npm/node etc, but it fails. Reminds me of the hassle I had getting brainbox to install/compile via nom on the Raspberry PI..lol

**Comment by virtualviolet** [comment]
bigmac:~ kevin$ /Applications/DeezLoader.app/Contents/MacOS/DeezLoader 
Server is running @ localhost:1730
Attempting connection to API
Attempting connection to API
2018-01-16 19:25:22.127 DeezLoader Helper[71968:3398202] Couldn't set selectedTextBackgroundColor from default ()
{ title: 'To the Sky',
  artist: 'Boris Blen',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '1/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201029',
  duration: '366',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Boris Blen - Goa 2012, Vol. 3/1 - Boris Blen - To the Sky.flac
Already downloaded: Boris Blen - To the Sky
{ title: 'Autumn Lights : Autumn Lights',
  artist: 'Vibrasphere',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '2/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201030',
  duration: '561',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Vibrasphere - Goa 2012, Vol. 3/2 - Vibrasphere - Autumn Lights _ Autumn Lights.flac
Already downloaded: Vibrasphere - Autumn Lights : Autumn Lights
{ title: 'Creationist',
  artist: 'Streamers',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '3/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201059',
  duration: '563',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Streamers - Goa 2012, Vol. 3/3 - Streamers - Creationist.flac
Already downloaded: Streamers - Creationist
{ title: 'Timeline',
  artist: 'Liquid Space',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '4/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'DEAR41215389',
  duration: '512',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Liquid Space - Goa 2012, Vol. 3/4 - Liquid Space - Timeline.flac
{ title: 'Timeline',
  artist: 'Liquid Space',
  album: 'Stomp or Die',
  performerInfo: 'Liquid Space',
  trackNumber: '3/3',
  partOfSet: '1/1',
  label: 'Prog On Syndicate',
  ISRC: 'DEAR41215389',
  duration: '516',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/a1efa9a58b21c81c71887b3f7f91d1e4/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Liquid Space - Stomp or Die/3 - Liquid Space - Timeline.flac
Already downloaded: Liquid Space - Timeline
{ title: 'Chasing Shadows',
  artist: 'Atom Device',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '5/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'USQY51247094',
  duration: '463',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Atom Device - Goa 2012, Vol. 3/5 - Atom Device - Chasing Shadows.flac
{ title: 'Chasing Shadows (Original Mix)',
  artist: 'Atom Device',
  album: 'Atom Device - Desert Eagle EP',
  performerInfo: 'Atom Device',
  trackNumber: '2/3',
  partOfSet: '1/1',
  label: 'Digital Nature Records',
  ISRC: 'USQY51247094',
  duration: '465',
  explicit: '0',
  genre: 'Dance',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/103d6122a035b3daf8fb45a315aff384/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Atom Device - Atom Device - Desert Eagle EP/2 - Atom Device - Chasing Shadows (Original Mix).flac
Failed to download: Atom Device - Chasing Shadows (Original Mix)
{ title: 'Today',
  artist: 'Hi Profile',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '6/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'DEAR22385438',
  duration: '583',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Hi Profile - Goa 2012, Vol. 3/6 - Hi Profile - Today.flac
{ title: 'Today (Original Mix)',
  artist: 'Hi Profile',
  album: 'Progstorm 3 Compiled By Querox',
  performerInfo: 'Various Artist',
  trackNumber: '7/9',
  partOfSet: '1/1',
  label: 'Prog On Syndicate',
  ISRC: 'DEAR41225492',
  duration: '586',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/9f67b3af4ce1e6a4e73f6ae8c293a091/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Hi Profile - Progstorm 3 Compiled By Querox/7 - Hi Profile - Today (Original Mix).flac
Already downloaded: Hi Profile - Today (Original Mix)
{ title: 'Almost Everything',
  artist: 'Impact',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '7/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'DELK11200063',
  duration: '416',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Impact - Goa 2012, Vol. 3/7 - Impact - Almost Everything.flac
Already downloaded: Impact - Almost Everything
{ title: 'Minds Mystery',
  artist: 'Lyctum',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '8/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201043',
  duration: '603',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Lyctum - Goa 2012, Vol. 3/8 - Lyctum - Minds Mystery.flac
Already downloaded: Lyctum - Minds Mystery
{ title: 'Here Today and Gone Tomorrow',
  artist: 'Drukverdeler',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '9/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201065',
  duration: '465',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Drukverdeler - Goa 2012, Vol. 3/9 - Drukverdeler - Here Today and Gone Tomorrow.flac
Already downloaded: Drukverdeler - Here Today and Gone Tomorrow
{ title: 'Higher Dimensional Space',
  artist: 'Inner State',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '10/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'DELK11200075',
  duration: '462',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Inner State - Goa 2012, Vol. 3/10 - Inner State - Higher Dimensional Space.flac
Already downloaded: Inner State - Higher Dimensional Space
{ title: 'Open Eyes',
  artist: 'Sonic Entity',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '11/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201087',
  duration: '477',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Sonic Entity - Goa 2012, Vol. 3/11 - Sonic Entity - Open Eyes.flac
Already downloaded: Sonic Entity - Open Eyes
{ title: 'Psycho Disco Balls',
  artist: 'Mr Peculiar',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '12/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'FR6V80226165',
  duration: '521',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Mr Peculiar - Goa 2012, Vol. 3/12 - Mr Peculiar - Psycho Disco Balls.flac
{ title: 'Psycho Disco Balls',
  artist: 'Mr Peculiar',
  album: 'Alternate Worlds',
  performerInfo: 'Mr Peculiar',
  trackNumber: '2/9',
  partOfSet: '1/1',
  label: 'Hadra Records',
  ISRC: 'FR6V80226165',
  duration: '522',
  explicit: '0',
  genre: 'Dance',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/7e0c3f6150f34ef95edbd6175a3d978c/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Mr Peculiar - Alternate Worlds/2 - Mr Peculiar - Psycho Disco Balls.flac
Already downloaded: Mr Peculiar - Psycho Disco Balls
{ title: 'Maitreya',
  artist: 'Mental Broadcast',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '13/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'USQY51266445',
  duration: '458',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Mental Broadcast - Goa 2012, Vol. 3/13 - Mental Broadcast - Maitreya.flac
{ title: 'Maitreya',
  artist: 'Mental Broadcast',
  album: 'Maitreya EP',
  performerInfo: 'Mental Broadcast, Sonic Species',
  trackNumber: '1/2',
  partOfSet: '1/1',
  label: 'Neurobiotic Records',
  ISRC: 'USQY51266445',
  duration: '460',
  explicit: '0',
  genre: 'Dance',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/5f65f41d56f06212460923986ff8388e/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Mental Broadcast - Maitreya EP/1 - Mental Broadcast - Maitreya.flac
Failed to download: Mental Broadcast - Maitreya
{ title: 'The Secret',
  artist: 'Champa',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '14/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201093',
  duration: '476',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Champa - Goa 2012, Vol. 3/14 - Champa - The Secret.flac
Already downloaded: Champa - The Secret
{ title: 'Push',
  artist: 'Quantum',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '15/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201100',
  duration: '457',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Quantum - Goa 2012, Vol. 3/15 - Quantum - Push.flac
{ title: 'Push (Original Mix)',
  artist: 'Quantum',
  album: 'Quantum - Push EP',
  performerInfo: 'Quantum',
  trackNumber: '1/4',
  partOfSet: '1/1',
  label: 'DNA Records',
  ISRC: 'USQY51266655',
  duration: '459',
  explicit: '0',
  genre: 'Dance',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/8614bd850684f2b6fd04302e1ef68324/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Quantum - Quantum - Push EP/1 - Quantum - Push (Original Mix).flac
Failed to download: Quantum - Push (Original Mix)
{ title: 'Forward',
  artist: 'Corona',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '16/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'DEMH90900083',
  duration: '371',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Corona - Goa 2012, Vol. 3/16 - Corona - Forward.flac
{ title: 'Forward',
  artist: 'Corona',
  album: 'Sonar Luminescene',
  performerInfo: 'Corona',
  trackNumber: '8/10',
  partOfSet: '1/1',
  label: 'Solar Tech Records',
  ISRC: 'DEMH90900083',
  duration: '374',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/6cc26f1d456f9d1d887dc076dccd4ade/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Corona - Sonar Luminescene/8 - Corona - Forward.flac
Already downloaded: Corona - Forward
{ title: 'Goahead',
  artist: 'Dejavoo',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '17/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'GBBYB1201054',
  duration: '441',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Dejavoo - Goa 2012, Vol. 3/17 - Dejavoo - Goahead.flac
Already downloaded: Dejavoo - Goahead
{ title: 'Resurrection : Resurrection',
  artist: 'Sinewave',
  album: 'Goa 2012, Vol. 3',
  performerInfo: 'Boris Blen',
  trackNumber: '18/18',
  partOfSet: '1/1',
  label: 'Yellow Sunshine Explosion',
  ISRC: 'USQY51253859',
  duration: '536',
  explicit: '0',
  genre: 'Electro',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/aaa0c1a3539546443711eb341626e1ad/1200x1200.jpg',
  year: '2012' }
Downloading file to /Volumes/Music/deezloader/Sinewave - Goa 2012, Vol. 3/18 - Sinewave - Resurrection _ Resurrection.flac
{ title: 'Resurrection (Champa Remix)',
  artist: 'Sinewave',
  album: 'Upxare EP',
  performerInfo: 'Champa',
  trackNumber: '2/2',
  partOfSet: '1/1',
  label: 'Neurobiotic Records',
  ISRC: 'USQY51253859',
  duration: '542',
  explicit: '0',
  genre: 'Dance',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/b9a7bbee335bf93dfb26e4c2b86882a0/1200x1200.jpg',
  year: '0000' }
Downloading file to /Volumes/Music/deezloader/Sinewave - Upxare EP/2 - Sinewave - Resurrection (Champa Remix).flac
Failed to download: Sinewave - Resurrection (Champa Remix)
Album finished: Goa 2012, Vol. 3

**Comment by virtualviolet** [comment]
The error about 'Already downloaded: xxxxxx' is very strange, all of the folders were deleted before trying to download again and they are empty.

**Comment by ExtendLord** [comment]
@virtualviolet I'm patching the problem in less than 1 hour.
I'm commiting a fix for US and crashes.

**Comment by ExtendLord** [comment]
@virtualviolet dfb3460ae0a83dd6981ab3d73db5eec08bc2a6f1
It should be fixed, if not, reopen the issue.
Adding a login window and 3.0.2 will be released
