### ISSUE TITLE
Will crash with older versions installed.

### ISSUE THREAD

**Issue by dekiller82** [ExtendLord/DeezLoader-Reborn#3]
I managed to fix it myself but it might be handy to include it in the readme.

So for the people that are trying to use this version but it keeps crashing delete the following directorys first!

C:\Users\[USERNAME]\AppData\Roaming\Deezloader
C:\Users\[USERNAME]\AppData\Local\Temp\deezloader-imgs

EDIT: Added info to the readme and created a pull-request but i'll leave this up in case people have the same issue and close it when the info is added.

**Comment by MiiLee94** [comment]
Should that fix my crashing, I'm downloading a playlist and it crashes on a song that is available in my country, and if I try to download that song only than it works, should I make a New Issue?

**Comment by ExtendLord** [comment]
@dekiller82 Maybe I will add a FAQ section and add it inside.

**Comment by dekiller82** [comment]
Seems good. As long as people know this is a known thing.
