### ISSUE TITLE
Save artwork image in album folder, save artwork size

### ISSUE THREAD

**Issue by mvusmvus** [ExtendLord/DeezLoader-Reborn#31]
I feel as though I didn't make myself clear last time. What I meant is that there should be an option to save album artwork into the folder of a downloaded album. SMLoader does that automatically, but there's currently no such option in DeezLoader.

One other thing - once the app is closed, the Artwork size reverts to default. That's a bug.

**Comment by ExtendLord** [comment]
https://github.com/ExtendLord/DeezLoader-Reborn/commit/514191f73fd73a33841109a91c4a1684d4993a59
Changed location of artworks to the albums folder.
It did not actually reverted it, its a bug.
