### ISSUE TITLE
downloading a song by Enrique Iglesias

### ISSUE THREAD

**Issue by froosti** [ExtendLord/DeezLoader-Reborn#35]
no matter what i try it always downloads a random song by Enrique Iglesias

**Comment by mvusmvus** [comment]
Perhaps the universe is trying to tell you something.

Seriously though, try downloading from another country's IP by using VPN software.

**Comment by ExtendLord** [comment]
I will commit an update and release 3.0.2 soon.
The update fixes alot of bugs including the US problem
