### ISSUE TITLE
More Tag in MP3 

### ISSUE THREAD

**Issue by WilCz** [ExtendLord/DeezLoader-Reborn#36]
Is it possible to include more data (Tag) to mp3? Example: **Label, BPM**
Thanks Developer for your support! Sorry for bad english

**Comment by mvusmvus** [comment]
The labels are already presented under the tag "Publisher". The BPMs are not because this data is not presented on Deezer. Try [Mp3Tag](https://www.mp3tag.de/en/download.html) + [Beatport script](https://forums.mp3tag.de/index.php?showtopic=14479) or [Foobar](http://www.foobar2000.org/download) + [BPM component](http://www.foobar2000.org/components/view/foo_bpm).

**Comment by syvhmx** [comment]
@mvusmvus there is data on BPM for tracks. Available on Deezer API:  
```
{
  "id": "3135556",
  "readable": true,
  "title": "Harder Better Faster Stronger",
  "title_short": "Harder Better Faster Stronger",
  "title_version": "",
  "isrc": "GBDUW0000059",
  "link": "https://www.deezer.com/track/3135556",
  "share": "http://www.deezer.com/track/3135556?utm_source=deezer&utm_content=track-3135556&utm_term=0_1516197357&utm_medium=web",
  "duration": "224",
  "track_position": 4,
  "disk_number": 1,
  "rank": "727696",
  "release_date": "2001-03-07",
  "explicit_lyrics": false,
  "preview": "https://e-cdns-preview-5.dzcdn.net/stream/51afcde9f56a132096c0496cc95eb24b-5.mp3",
  "bpm": 123,
  "gain": -12.4,
```  
If you can't search for it, doesn't mean it's not available in the API.

**Comment by hee6933** [comment]
I have downloaded the same song with both SMLoadr and this program and SMLoadr has additional BPM and Publisher tags.

**Comment by hee6933** [comment]
I have downloaded some songs with both SMLoadr and this program and SMLoadr has additional BPM and Publisher tags. It also has 1400x1400 covers compared to 1200x1200.

**Comment by ExtendLord** [comment]
@hee6933 I will add to the next update 1500p which is the biggest supported image on deezer

**Comment by WilCz** [comment]
Not all the library of deezer have cover art 1400x1400, the new track yes: 1400x1400, 1500x1500 for default: 1200x1200, sorry for bad english
