### ISSUE TITLE
Build issue with icons

### ISSUE THREAD

**Issue by sigzegv** [ExtendLord/DeezLoader-Reborn#37]
When compiling with compile.sh (archlinux here). It fails when stating a file named `res/icon.ico.icns` and it required app icns2png app to build (but I really don't know who should provide it ? user or npm ?

**Comment by ExtendLord** [comment]
Try npm install && npm run dist or yarn install && yarn run dist .
If neither works then it is probably electron builders problem.

**Comment by ExtendLord** [comment]
I'm commiting an update for this issue and also releasing 3.0.2.
If the issue still exists reopen the issue.
