### ISSUE TITLE
downloading incorrect song

### ISSUE THREAD

**Issue by yooda120** [ExtendLord/DeezLoader-Reborn#39]
for some reason it's download incorrect song..
no matter what i'm trying to download i get only this song ..
"1 - Enrique Iglesias - EL BANO"
HeLp Me:)

**Comment by ExtendLord** [comment]
@yooda120 I'm releasing a fix for that.
You are probably from US, that is the problem.
I'm fixing and releasing 3.0.2 so watch this repo

**Comment by yooda120** [comment]
Wow!! 
you are the best i've seen tanks!!!
