### ISSUE TITLE
Artwork not working

### ISSUE THREAD

**Issue by Clementzz** [ExtendLord/DeezLoader-Reborn#43]
Hi, everything was fine for me before updating to 3.0
Now there's no artwork on every track I download.

I tried uninstall/reinstall, use 3.0.0 and 3.0.1 but it doesn't work..
Also in my settings page I can't click anywhere around "artwork" size, but in my settings file it's set to "\1200x1200.jpg".

![screenshot](https://user-images.githubusercontent.com/35542152/35064452-6810d264-fbca-11e7-9419-04009251d946.png)

Any idea of why it's not working? Thanks in advance :)

**Comment by Clementzz** [comment]
Mm also can someone explain me how to update from github? I'm a bit lost with this ^^

**Comment by ExtendLord** [comment]
Maybe you do not have permissions?
What is your OS?
Can you run it using terminal/cmd and send me the errors from the cmd if any?

**Comment by Clementzz** [comment]
Don't think it comes from permission.. I'm on W10

cmd while downloading:

Server is running @ localhost:1730
Attempting connection to API
{ title: 'With Or Without You (Remastered 2007)',
  artist: 'U2',
  album: 'The Joshua Tree (Deluxe Edition Remastered)',
  performerInfo: 'U2',
  trackNumber: '3/25',
  partOfSet: '1/2',
  label: 'Universal Music Division Barclay',
  ISRC: 'GBUM70709792',
  duration: '295',
  explicit: '0',
  genre: 'Alternative',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/b255afa51b3c1af7872acb56da319c2dundefined',
  year: '2007' }
Downloading file to C:\Users\Cl├®ment\Music\Deezloader\U2 - With Or Without You (Remastered 2007).mp3
Downloaded: U2 - With Or Without You (Remastered 2007)

Here it is, can you explain me btw how to install updates from github? :)

**Comment by ExtendLord** [comment]
@Clementzz Download 3.0.2 from github, I have released 3.0.2 and try again.

**Comment by Clementzz** [comment]
I'll try this @ExtendLord but don't know how to install from github cause there's no .exe (I'm a github beginner haha)

**Comment by ExtendLord** [comment]
@Clementzz
1. Download and install https://nodejs.org/dist/v9.4.0/node-v9.4.0-x64.msi (Node JS)
2. Download the zip file by clicking "Clone or download" and then you extract it somewhere and then you run compile.bat.
3. You go to /dist folder and you will see the installer and inside the win-unpacked folder you will see the deezloader folder.
4. Currently the github version equals the release version.

**Comment by Clementzz** [comment]
Ok thanks a lot for the explanations, yes I saw it the versions are the same so I downloaded the .exe ^^

So same problem, I can't change the setting and there's still no artwork..

Less information in cmd btw:

Server is running @ localhost:1730
Downloading file to C:\Users\Cl├®ment\Music\Deezloader\Coldplay - Hymn For The Weekend.mp3
Downloaded: Coldplay - Hymn For The Weekend

I saw that in the previous cmd we had a link to the artwork (not working btw) and now we don't. Maybe this link was and is wrong for any track.. Is your link working when you open it in a browser? 

It was this link: 
https://e-cdns-images.dzcdn.net/images/cover/b255afa51b3c1af7872acb56da319c2dundefined

**Comment by ExtendLord** [comment]
@Clementzz Delete %appdata%/Deezloader and %localappdata%/Deezloader and try again, maybe that is the problem.

**Comment by Clementzz** [comment]
@ExtendLord Done, nothing changes.. Nothing in cmd too

**Comment by axllent** [comment]
I think there may be a problem with the saving of settings. I'm experiencing something I believe is related, when I select a default `Artwork size` in settings and restart the app it goes back to 1200x1200.

**Comment by Clementzz** [comment]
@axllent The problem is that I can't select anything about the `Artwork size` in the settings tab, as you can see on my first screenshot above.

Your setting is going back to 1200 but does it work anyway?

**Comment by axllent** [comment]
@Clementzz If I set it to 800x800 it works for that session, until I restart the app, then it goes back to 1200x1200.

**Comment by Clementzz** [comment]
@axllent Ok well it can be linked

**Comment by Clementzz** [comment]
@axllent whay do you have around the `Artwork size` tag?
![screenshot](https://user-images.githubusercontent.com/35542152/35067419-1ad74758-fbd4-11e7-8098-75682f6ab6f4.png)

**Comment by axllent** [comment]
@Clementzz Sorry, I don't understand the question "whay do you have around the Artwork size tag?" If you're meaning "what do I see"...

![settings](https://user-images.githubusercontent.com/1463435/35067829-15f21d56-fc3a-11e7-9922-90d7d9f692b9.png)

**Comment by Clementzz** [comment]
@axllent yes I was meaning "what do you see", sorry ^^'
Ok so you see a list, that's so strange I have no menu, nothing for this setting.. 😒

**Comment by Clementzz** [comment]
@ExtendLord Any other idea? Am I the only one to have this problem? I also tried on another PC and it works fine, that's so strange! The `Charts` tab's not loading too, and I really think this can be linked.
