### ISSUE TITLE
FLAC versions not downloading

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#44]
Mentioned this in another issue post, thought i would open a new one.

Some tracks only seem to be available as MP3, can anyone confirm if this is known issue with Deezer?

**Console output:**
Downloading file to X:\test3\Various Artists - Portal of Perceptions\1 - Ishq - Aphrodite.flac
Failed to download: Ishq - Aphrodite
Downloading file to X:\test3\Various Artists - Portal of Perceptions\2 - Makyo - Jasmine.flac
Failed to download: Makyo - Jasmine
Downloading file to X:\test3\Various Artists - Portal of Perceptions\3 - Adham Shaikh - Ohm (Transfix mix).flac
Failed to download: Adham Shaikh - Ohm (Transfix mix)
Downloading file to X:\test3\Various Artists - Portal of Perceptions\4 - Aes Dana - Haze (Celestrial Mix).flac
Failed to download: Aes Dana - Haze (Celestrial Mix)
Downloading file to X:\test3\Various Artists - Portal of Perceptions\5 - Androcell - Caribbeyond.flac
Failed to download: Androcell - Caribbeyond
Downloading file to X:\test3\Various Artists - Portal of Perceptions\6 - Cell - Twisted Sun.flac
Failed to download: Cell - Twisted Sun
Downloading file to X:\test3\Various Artists - Portal of Perceptions\7 - Androcell - Fungus Garden (Acoustic mix).flac
Failed to download: Androcell - Fungus Garden (Acoustic mix)
Downloading file to X:\test3\Various Artists - Portal of Perceptions\8 - H.U.V.A. NETWORK - Rain Geometries (Solar Fields remix).flac
Failed to download: H.U.V.A. NETWORK - Rain Geometries (Solar Fields remix)
Downloading file to X:\test3\Various Artists - Portal of Perceptions\9 - Ishq - El Morya.flac
Failed to download: Ishq - El Morya
Album finished: Portal of Perceptions

And then a few tracks from above with HIFI disabled...

**Console output:**
Downloading file to X:\test3\3 - Adham Shaikh - Ohm (Transfix mix) - Portal of Perceptions.mp3
Downloaded: Adham Shaikh - Ohm (Transfix mix)
Downloading file to X:\test3\2 - Makyo - Jasmine - Portal of Perceptions.mp3
Downloaded: Makyo - Jasmine
Downloading file to X:\test3\1 - Ishq - Aphrodite - Portal of Perceptions.mp3
Downloaded: Ishq - Aphrodite

**Comment by virtualviolet** [comment]
And then a few tracks from above with HIFI disabled...

**Console output:**
Downloading file to X:\test3\3 - Adham Shaikh - Ohm (Transfix mix) - Portal of Perceptions.mp3
Downloaded: Adham Shaikh - Ohm (Transfix mix)
Downloading file to X:\test3\2 - Makyo - Jasmine - Portal of Perceptions.mp3
Downloaded: Makyo - Jasmine
Downloading file to X:\test3\1 - Ishq - Aphrodite - Portal of Perceptions.mp3
Downloaded: Ishq - Aphrodite

**Comment by ExtendLord** [comment]
@virtualviolet Send link for the album/playlist.

**Comment by virtualviolet** [comment]
http://www.deezer.com/en/album/571264

**Comment by ExtendLord** [comment]
@virtualviolet The track is only available in mp3 that is why

**Comment by virtualviolet** [comment]
So did some googling and a little talking to a few friends who own labels, it's Deezer or the label distribution. Deezer only started offering FLAC last year and many labels only uploaded MP3, now they upload both. So older releases are unlikely to be available as FLAC.

**Comment by ExtendLord** [comment]
I will add a fallback for mp3 even with HIFI mode.

**Comment by virtualviolet** [comment]
good man, that would help I guess. I'm now just downloading MP3 :-( The plan was to convert flac to AAC.

**Comment by virtualviolet** [comment]
Does the API provide information about the file types available?
