### ISSUE TITLE
Genre tag changes with language

### ISSUE THREAD

**Issue by hee6933** [ExtendLord/DeezLoader-Reborn#48]
I cannot confirm it if it's changing with the system language but the same song downloaded with 3.0.1 had English word for the genre while the one downloaded with 3.0.2 didn't.

**Comment by ExtendLord** [comment]
Give me the album or track that you have downloaded

**Comment by hee6933** [comment]
For example, Getter - Forget It, when downloaded with 3.0.1 has genre tag "Dance", but has "Dans" when downloaded with 3.0.2. I tried to create another account from US, but Deezer still manages to find where I am when I use VPN's, another browser and a private tab.

**Comment by ExtendLord** [comment]
I have downloaded this and the genre is Dance :/
Dont use a VPN.
The genre should be the same

**Comment by hee6933** [comment]
Is Dance in your language?
I have downloaded all the songs without vpn. But because you said don't use it, I downloaded again with a VPN from US, and It now says Dance again.

**Comment by ExtendLord** [comment]
Maybe it depends on the country you are on.
Not because of the software, but because of Deezer.
I'm not from a country that speaks English natively and the genre I got is Dance
