### ISSUE TITLE
Add option to skip log in or save log in details

### ISSUE THREAD

**Issue by GithubUser5462** [ExtendLord/DeezLoader-Reborn#50]
The log in requirement was added to circumvent the problems that some users were facing.
Unfortunately this change made the app more tedious to use.

It would be nice if there was an option to either store the login info or skip the login screen if you are not affected by the problems.
 
PS: The form in the app asks you for the username, but what you actually have to type in is the e-mail address.

**Comment by ExtendLord** [comment]
I will fix and release 3.0.3 tomorrow.

**Comment by GithubUser5462** [comment]
Thank you!

**Comment by NicolasPL64** [comment]
OMG! YESSS!!

**Comment by ExtendLord** [comment]
@virtualviolet @NicolasPL64 @GithubUser5462 Added https://github.com/ExtendLord/DeezLoader-Reborn/commit/626bdfec97f9e34dae74147f3ac2a5199181548c
I will release 3.0.3 soon.
