### ISSUE TITLE
Add an updater or an update alert!

### ISSUE THREAD

**Issue by NicolasPL64** [ExtendLord/DeezLoader-Reborn#53]
You can add an alert when there is a new update? Or an auto updater :3 
Sry 4 my english. I'm spanish xDDD

**Comment by ExtendLord** [comment]
Added https://github.com/ExtendLord/DeezLoader-Reborn/commit/4ae71f9eb8692bd2886530630c60f87869bee869

**Comment by NicolasPL64** [comment]
Give me a child pls :D xDDDDD OMG love you much lollol
