### ISSUE TITLE
Add auto-login & exit button on login page

### ISSUE THREAD

**Issue by Abdulaziz-IT** [ExtendLord/DeezLoader-Reborn#55]
Hello, thank you for maintaining this, but can you make the login page have auto-login? so that I don't have to re-type my e-mail & password everytime.

Besides, I don't think it's a bad idea to add "exit" button anywhere in the GUI so that I can exit the program (In login page)

**Comment by cudrstk** [comment]
I'm with you with the auto-login. But why would you need an exit button?

**Comment by Uchun** [comment]
@Abdulaziz-IT you can exit the app by closing its window, what's the problem with that? :smile:
