### ISSUE TITLE
Add donation address

### ISSUE THREAD

**Issue by mastad0n** [ExtendLord/DeezLoader-Reborn#58]
I see so many requests from people, would be nice if people gave you something in return.

I suggest adding your Monero address, since Bitcoin fees are insanely high right now.

**Comment by ExtendLord** [comment]
@mastad0n There is a donation inside the software, I will add donation into the README.

**Comment by mastad0n** [comment]
Sounds good, I didn't see it.

**Comment by virtualviolet** [comment]
I think it is only fair ;-)

**Comment by ExtendLord** [comment]
Added https://github.com/ExtendLord/DeezLoader-Reborn/commit/c1bfff9fc610d58d9109eaa4575e42c4ee152792
