### ISSUE TITLE
App Crashing on Download 

### ISSUE THREAD

**Issue by nasedase** [ExtendLord/DeezLoader-Reborn#59]
Using both Arch Linux and Ubuntu 64 bit version 3.0.2. crashes immediately after clicking the download button.

**Comment by ExtendLord** [comment]
@nasedase Fixed https://github.com/ExtendLord/DeezLoader-Reborn/commit/626bdfec97f9e34dae74147f3ac2a5199181548c
Please compile the project and try again.
The issue was your login details being incorrect(The software had problems detecting it.)

**Comment by BarbzYHOOL** [comment]
Works perfectly fine for me on ubuntu (just wanted to say thx)
