### ISSUE TITLE
Add genre + part (eg: disc 1 of 2) tag

### ISSUE THREAD

**Issue by syvhmx** [ExtendLord/DeezLoader-Reborn#6]
It seems incomplete that a song does not have a genre tag, especially.  
And so far, I've used and looked into other downloader and source code and tried it myself,  
but to no avail (genre shows 'undefined').  

Edit: I found from the Deezer Developer API for the genre tag, which is available in the album under the string "genre_id" and "genres" - "name" (looking through API Explorer)

Sample code:
https://pastebin.com/LCm1qrpE

The part tag (Disc number) goes 'undefined'.  
I saw that in the Deezer API, it uses "disk_number" instead of "disc_number" in Deezloader Reborn.  
Maybe you could check it?

**Comment by ExtendLord** [comment]
@syvhmx Fixed as a part of Tags Update

66bcf7731ea5886a099ae39952c4e5a183b29713
