### ISSUE TITLE
Deezer support FLAC-HD?

### ISSUE THREAD

**Issue by BNFCTR** [ExtendLord/DeezLoader-Reborn#61]
I'm just asking that do you know if Deezer has FLAC-HD (2500-3500kb/sn - 96.0kHz - 24 bits) versions of songs and if so can we download them?

**Comment by ExtendLord** [comment]
@BNFCTR Not as far as I know

**Comment by syvhmx** [comment]
@BNFCTR Not all songs are available as Hi-Res FLAC (24-bit) in Deezer.  
Some do have 24-bit ones, like:
`Joseph Vincent - Location`
Maybe the publisher/Deezer itself prefers 16-bit.

**Comment by MatYRicS** [comment]
How do you check if a song is avabile in FLAC-HD??

**Comment by syvhmx** [comment]
You don't.  
If it's available, then you're lucky.
