### ISSUE TITLE
ARM architecture support?

### ISSUE THREAD

**Issue by jones1008** [ExtendLord/DeezLoader-Reborn#62]
Compiling this software on a arm based architecture does not work:
```
Error: Unsupported arch arm
    at archFromString (/root/DeezLoader-Reborn-master/node_modules/electron-builder/node_modules/builder-util/src/arch.ts:27:13)
    at computeArchToTargetNamesMap (/root/DeezLoader-Reborn-master/node_modules/electron-builder/node_modules/electron-builder-lib/src/targets/targetFactory.ts:36:18)
    at /root/DeezLoader-Reborn-master/node_modules/electron-builder/node_modules/electron-builder-lib/src/packager.ts:348:41
    at Generator.next (<anonymous>)
```
Are you planning to make it compileable on a arm based computer too?

**Comment by ExtendLord** [comment]
@jones1008 What is your OS?

**Comment by jones1008** [comment]
I am running debian jessie.

**Comment by FrozenAlex** [comment]
@jones1008 You could try running it as a web server with some source editing.

**Comment by jones1008** [comment]
I actually got the deleted deezloader-server npm repository (which I downloaded before it was deleted) working on my web server and thanks to [this little trick](https://www.reddit.com/r/Piracy/comments/7pocwe/rip_deezloader/dsl061k/) got the old deezloader working... I now just have to build myself a script that automatically updates the Cookie-SID...

So basically I don't need any support on this now, but if someone has interest in this software working on arm based devices you can keep it open, otherwise you can close it.
