### ISSUE TITLE
Downloads Failed

### ISSUE THREAD

**Issue by DagiBeeast** [ExtendLord/DeezLoader-Reborn#64]
Hi,

i am new to DeezLoader-Reborn and i think this: http://prntscr.com/i2avbf isnt normal?!? Or maybe its normal? And what can i do against it, download the failed songs manually?

greetings form Germany ;) (sorry for my bad english -.-)

Basti

**Comment by ExtendLord** [comment]
Sent me the playlists please.

**Comment by DagiBeeast** [comment]
http://www.deezer.com/de/playlist/4047371782

**Comment by ExtendLord** [comment]
@DagiBeeast What about the playlist of the Hardrock/Metal

**Comment by DagiBeeast** [comment]
At HardRock/Metal, its the same problem...

**Comment by ExtendLord** [comment]
It returns Album not found error hmm.
I will change the way that the software gets the tracks from the playlist.
And no its not normal.

**Comment by DagiBeeast** [comment]
Lol... Thank you very much!

**Comment by DagiBeeast** [comment]
Have you fixed it yet? Or is it a major problem that you can´t "influence"?

**Comment by ExtendLord** [comment]
@DagiBeeast Fixed it just now.
Did you really though that it would never be fixed?
https://github.com/ExtendLord/DeezLoader-Reborn/commit/f6354365ac0928bfa3c70ca56f32ffa4f0538371
