### ISSUE TITLE
Playlist track number error

### ISSUE THREAD

**Issue by sNiPE18** [ExtendLord/DeezLoader-Reborn#65]
Hi, firstable i want thank you for these great work. 
I got some issue when downloading playlists and also by some Album. The trackname numbers are several times the same. This phenomenon is occurred since the version 3.0! 
For example: Album: https://prnt.sc/i2dur0 Playlist: https://prnt.sc/i2efkp
Thank you very much.

**Comment by ExtendLord** [comment]
2 Problems

1. There are more than 1 discs and the track number does down to 1 each disc.
2. Playlists track numbers are the albums one.
I will fix it in 3.0.4

**Comment by ThePlayingGoblin** [comment]
@ExtendLord, could you also make the numbering like this:
1. Martin Garrix - Animals
instead of:
1 - Martin Garrix - Animals
It just looks better :)

**Comment by ExtendLord** [comment]
#26 Duplicate
