### ISSUE TITLE
Full date

### ISSUE THREAD

**Issue by Aqluse** [ExtendLord/DeezLoader-Reborn#66]
Any chances to get date into tags? Preferrable to put it into COMMENTS field

**Comment by syvhmx** [comment]
Full date meaning 2017-09-21 format?
It's the same as year tag, except it has been cut to 4 digits only.

**Comment by Aqluse** [comment]
@syvhmx Yes, I meant that format

**Comment by ExtendLord** [comment]
https://github.com/ExtendLord/DeezLoader-Reborn/commit/0d03eb091912d9f637d6edc4f7a249586f8c617b
Now there is both date and year for MP3 and FLAC.
