### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by ThePlayingGoblin** [ExtendLord/DeezLoader-Reborn#68]
Would it be possible to add proxy setting to the client?

**Comment by ExtendLord** [comment]
Why do you need proxy just for deezloader?

**Comment by ThePlayingGoblin** [comment]
Make us anonymous, and changes our region. Can download albums we normally can't in the country we are in.

**Comment by ExtendLord** [comment]
DeezLoader bypasses unavailable tracks(for certain countries, if it is unavailable in general then nope)
And you can just use a VPN or put your proxy on your system
Closed.
