### ISSUE TITLE
Download from URL not recognizing URL.

### ISSUE THREAD

**Issue by ReginaldCFlores** [ExtendLord/DeezLoader-Reborn#69]
I managed to download a playlist through the URL function. Went to go download a second one and it wouldn't read the URL. It won't read any URL.

**Comment by Uchun** [comment]
@ReginaldCFlores 
Try again with the same playlist on another PC and latest version of DeezLoader-Reborn.
Provide more info: playlists urls, OS & DeezLoader-Reborn version, start DeezLoader-Reborn from command line and provide logs from it when trying to download again and it doesn't go.
