### ISSUE TITLE
DeezLoader like a script

### ISSUE THREAD

**Issue by KGB-USSR** [ExtendLord/DeezLoader-Reborn#70]
Can you explain how to use the DeezLoader script in cmd?

**Comment by ExtendLord** [comment]
What do you mean?

**Comment by KGB-USSR** [comment]
Like this script https://github.com/svbnet/RedSea

**Comment by ExtendLord** [comment]
If you mean a cmd command for deezloader, there is no command for it.

**Comment by KGB-USSR** [comment]
Ok. Thanks.
