### ISSUE TITLE
Fix tag track/track, disc/disc and add label

### ISSUE THREAD

**Issue by WilCz** [ExtendLord/DeezLoader-Reborn#74]
The tag of the track: Example: track: 1/12, Disc: 1/1 and add label
![fixtag](https://user-images.githubusercontent.com/35513125/35159823-1801d574-fd01-11e7-93b6-625c8bbb61ec.png)

**Comment by ExtendLord** [comment]
Is it mp3 or flac?

**Comment by WilCz** [comment]
In the format mp3 deezloader 3.0.3, in the version 3.0.2 work good no problems en tag: tracks: 1/11 and disc: 1/1

**Comment by ExtendLord** [comment]
https://github.com/ExtendLord/DeezLoader-Reborn/commit/65f2b046b499f629f5d2c1cb865a6502e120aacd
Fixed the tags.

**Comment by syvhmx** [comment]
Composer tag 'undefined' if unavailable, same as genre tag before.

**Comment by Uchun** [comment]
@syvhmx 

> Composer tag 'undefined' if unavailable, same as genre tag before.

Open new issue please, provide example track/URL.
