### ISSUE TITLE
Adds extra/blank time in MP3 (compared Deezloader downloaded file with DeezLoader-Reborn downloaded file)

### ISSUE THREAD

**Issue by WebCoderX** [ExtendLord/DeezLoader-Reborn#75]
Here are the comparisons:

Deezloader:
https://i.imgur.com/DaMebzE.jpg

Deezloader-Reborn:
https://i.imgur.com/BgzokoC.jpg

Notice the extra/blank   audio/time at the end of the spectrogram of DeezLoader-Reborn.
At first I though it was only SPEK showing a bigger graph, its not (its some kind of a bug, because why doesn't SPEK show a bigger graph in Deezloader's downloaded file. Also I compared 4 files to reach this conclusion)

Note: From a collector's/audiophile's perspective :)

**Comment by Uchun** [comment]
@WebCoderX 

> its not

How can you be sure it's not because of Spek just by trying something 5 times **in Spek only**, lol? Use your mind, check in another software first.

Also, try to remove all ID3 tags from both mp3s first (e.g. using [Mp3tag](https://www.mp3tag.de/en/)) and compare again - this is a common Spek issue with showing different length because of some different tags.

**Comment by ExtendLord** [comment]
@Uchun is right.
As I just checked now the problem is spek.
Because of the tags, without the tags, the mp3's are identical.
So no issue here.

**Comment by WebCoderX** [comment]
@ExtendLord 
"Because of the tags, without the tags, the mp3's are identical"

Sorry did not understand?

**Comment by ExtendLord** [comment]
The mp3 from deezloader reborn has no space there, it thinks like that because of the tags.
The duration tag is 205 sec which is 3:25.
Bugs with spek

**Comment by Uchun** [comment]
@WebCoderX 
Hi there, my account was erroneously auto-flagged by github spam-bot and hidden from public, so you couldn't see my message and got inconsistent discussion. Now you can see my answer above.

**Comment by WebCoderX** [comment]
@ExtendLord 
@Uchun 
I feel so dumb lol!
I never thought about checking the tags 😞 
Sorry for disturbing you so much @ExtendLord
