### ISSUE TITLE
Next step: Log out button

### ISSUE THREAD

**Issue by NicolasPL64** [ExtendLord/DeezLoader-Reborn#78]
You've added auto login button, but when I need to log out?? xDDDDDDD
i'll waiting your answer kek

**Comment by ExtendLord** [comment]
You don't need to, just don't lol.
If you will change your accounts password, it will not pass the login page and you will be able to replace the account.
Another way is to delete the 'autologin' file from %appdata%/Deezloader

**Comment by NicolasPL64** [comment]
mmm ok... xdxd
