### ISSUE TITLE
Add log window

### ISSUE THREAD

**Issue by majikagun** [ExtendLord/DeezLoader-Reborn#8]
Can you add a log so we can see what the program is downloading especially when downloading a playlist. That would be great if you add this. Thanks

**Comment by ExtendLord** [comment]
@majikagun I need more explanation.
If you want to see the files you are downloading just go to Downloads section.

**Comment by majikagun** [comment]
I mean when you are downloading a  playlist. We can't see what the program is downloading. Only the number of songs and number of failed.
