### ISSUE TITLE
Scroll to top... ¿bug?

### ISSUE THREAD

**Issue by NicolasPL64** [ExtendLord/DeezLoader-Reborn#81]
Scroll down and the click on scroll to top button. the text gets static. Look it, remember that i dont speak english well and i cant explain it xD

**Comment by ExtendLord** [comment]
I don't know what you are talking about, I can still copy the text after scrolling up with the button.

**Comment by NicolasPL64** [comment]
The text that says "Scroll to top" in the arrow pointing up

**Comment by NicolasPL64** [comment]
Look. Down right in the corner
That text lol my english is shit, srusly
![image](https://user-images.githubusercontent.com/31411531/35174052-e9f95ffe-fd3b-11e7-9276-adf060792431.png)

**Comment by Uchun** [comment]
@NicolasPL64 
Do you mean like this?
![snapshot](https://user-images.githubusercontent.com/35609161/35183931-e0465a70-fde5-11e7-9d98-2985aace61b6.png)

In that case, it should disappear when you move your mouse cursor away from scroll-to-top button. And when you move cursor over button again - text should be near button again.
