### ISSUE TITLE
Pasting (CMD + V) doesn't work in the search bar in Macos.

### ISSUE THREAD

**Issue by ashven288** [ExtendLord/DeezLoader-Reborn#85]
Selecting all (CMD +A) and also copying (CMD + C) also doesn't work from the search bar. I'm on version 3.0.3.

**Comment by ExtendLord** [comment]
Not sure why you cant copy paste on the search bar.
I have no issues doing that.

**Comment by ashven288** [comment]
I can only right click then copy/cut/paste things. On Mac 10.13.2.

**Comment by ExtendLord** [comment]
Then its not related here, you have issues with mac, not deezloader
