### ISSUE TITLE
first 9 tracks number ## instead of #

### ISSUE THREAD

**Issue by didiou** [ExtendLord/DeezLoader-Reborn#86]
[french user]
First great job !
Hello, is it possible to rename the 9 first numbers 1->9 to 01, 02,... 09 please ?
Thanks !

**Comment by ExtendLord** [comment]
No

**Comment by Uukrull** [comment]
@didiou: You can do that if you change this [line](https://github.com/ExtendLord/DeezLoader-Reborn/blob/514191f73fd73a33841109a91c4a1684d4993a59/app/app.js#L1214) to:

`    return i > 0 ? pad(str.slice(0, i), 2) : str;`

**Comment by ExtendLord** [comment]
I can but its not a practical thing to do in tags.
I rather leave it as it is.

**Comment by Uchun** [comment]
My guess is the author would want this not in tags, but in filenames. At least when there are more than 9 tracks (so files too).
At least I would want it :smile:

**Comment by Uukrull** [comment]
> My guess is the author would want this not in tags, but in filenames.

That's what my fix does (I can't stand single digit track numbers in filenames :) )

**Comment by didiou** [comment]
Yes, it's what i want (in the first 9 filenames) !
Thanks.
