### ISSUE TITLE
Possible to stream?

### ISSUE THREAD

**Issue by jackpot08** [ExtendLord/DeezLoader-Reborn#87]
Is there a way to make it so you can stream and buffer songs and have media control (manually select and scroll through song)

**Comment by ExtendLord** [comment]
What do you mean?
You want deezloader to play musics?

**Comment by jackpot08** [comment]
Yes, if we could listen to the song before downloading

**Comment by ExtendLord** [comment]
Sorry but no, unless somebody will pull request
