### ISSUE TITLE
crash after download

### ISSUE THREAD

**Issue by anepwanpis** [ExtendLord/DeezLoader-Reborn#88]
after hit the download button it crash after a few moments

**Comment by ExtendLord** [comment]
Run deezloader using cmd or terminal and after it crashes, post here the logs

**Comment by AiFulDev** [comment]
I have the same issue with the latest version. Here is a screen of the logs in cmd:
![deezloader303rebornlogs](https://user-images.githubusercontent.com/32014004/35183377-483da18e-fde5-11e7-9c81-79fb7e8c11e6.PNG)

**Comment by IvanTurgenev** [comment]
Same here
![screenshot from 2018-01-20 11-19-10](https://user-images.githubusercontent.com/3318444/35185513-cd2a463e-fdd3-11e7-866c-aaa96bdc21cb.png)

**Comment by JackyNiew** [comment]
Hi!
I confirm, identical problem....

**Comment by ExtendLord** [comment]
@JackyNiew @IvanTurgenev @AiFulDev @anepwanpis Can you please download the zip file of the repository and compile it and try again?
It should be fixed.
And of course repeat the process(Don't forget to delete the folders).

**Comment by JackyNiew** [comment]
Hi!
I am under windows 10, I do not know how to compile the contents of the zip file ...
Thank you for giving me the procedure to follow ...

**Comment by JackyNiew** [comment]
Thanks !!!

**Comment by AiFulDev** [comment]
It works @ExtendLord ! Thanks !!!
![capture](https://user-images.githubusercontent.com/32014004/35245772-a4f09c70-ffc4-11e7-9624-88677595aed3.PNG)

**Comment by JackyNiew** [comment]
Crash during the second download.
[Capture.txt](https://github.com/ExtendLord/DeezLoader-Reborn/files/1653818/Capture.txt)

**Comment by ExtendLord** [comment]
@JackyNiew Redownload the zip, delete the project and extract again.
https://github.com/ExtendLord/DeezLoader-Reborn/commit/789042521a60e87f80a905bd26914931431ea1de
It should fail now instead.

**Comment by JackyNiew** [comment]
It's OK! Thank you !...
