### ISSUE TITLE
"Downloads" list cleared after exit/crash

### ISSUE THREAD

**Issue by geekeyz** [ExtendLord/DeezLoader-Reborn#91]
When a list is being downloaded : if I exit the software or if it crashes, the list is deleted and the downloads don't resume...

**Comment by ExtendLord** [comment]
It should be like that.

**Comment by geekeyz** [comment]
I don't get it... I think it's not easy to remember all the artists/songs that were in the queue if the software crashes or if I have to exit for some reason... I think this feature could be great, but in this case the "clear list" button should also cancel every file in the queue (it only removes downloaded files at the moment).
