### ISSUE TITLE
Url with spaces 

### ISSUE THREAD

**Issue by eraser-head** [ExtendLord/DeezLoader-Reborn#93]
Thanks por the app, it's awesome. I wach that when the url from you are downloading the app does nothing, for example this

http://www.deezer.com/search/Shudder%20to%20Think/album

if you copy the url from browser and them paste it, it add a %20, but the app doesn't start a donwload, with spaces, without them, or with %20

thanks!

**Comment by ExtendLord** [comment]
You can't use that link to download.
You need a https://www.deezer.com/(playlist/album/track)/{id}
No spaces even needed.
