### ISSUE TITLE
No artwork on FLAC downloads

### ISSUE THREAD

**Issue by Cilusse** [ExtendLord/DeezLoader-Reborn#94]
Hello!

Thank you very much for maintaining this project again, feels good to have a new version.

Being able to download songs in FLAC is awesome, however there is no artwork for them.
Is it a restriction of the FLAC format and the ID3 tags that it can support, or just a bug ?

If this is a real restriction, I would suggest that the artwork gets saved as .png next to the downloaded file.

Thank you :)

**Comment by ExtendLord** [comment]
https://github.com/ExtendLord/DeezLoader-Reborn/commit/514191f73fd73a33841109a91c4a1684d4993a59
Albums artwork is now inside the album.

**Comment by dylanbroome** [comment]
Could you also maybe add an option to not download the png file of the artwork, or have the option to relocate it?
