### ISSUE TITLE
File type parameter

### ISSUE THREAD

**Issue by 12au7** [ExtendLord/DeezLoader-Reborn#95]
Mainly for when custom folder names get implemented, adding the %filetype% parameter would allow us to name folders based on the file type, either FLAC or MP3, however that may be difficult seeing as the folder is probably created before it can check if the file is MP3 or FLAC

**Comment by 12au7** [comment]
Didn't realize a similar folder name issue was already open, changing issue to file type parameter

**Comment by ExtendLord** [comment]
I don't think I will add a filetype parameter.
It is not necessary.
