### ISSUE TITLE
Login Failed Multiply Times

### ISSUE THREAD

**Issue by DJKenzoDE** [ExtendLord/DeezLoader-Reborn#96]
Hey Guys,

i have a Problem to Login in Deezloader
It say my data is incorrect but i can login with the data on my phone and on the homepage from deezer.

Have anyone maybe a Version without the login?

Infos (For mor Infos write it down pls)
Country: Germany - Berlin
OS: Windows 7 x64 With Latest Update
Date Download: 20.01.2018 (dd.mm.yyyy)
Date Problem: 20.01.2018 (dd.mm.yyyy)
Version: 3.0.3 

I have Downloaded from the given Mega link and i have it compiled but the same problem

Greetz from Germany.

**Comment by ExtendLord** [comment]
Did you entered an email or a username?

**Comment by ExtendLord** [comment]
Closed due to not answering for 2 days.
Answer the question if you want it to be opened.
