### ISSUE TITLE
Auto login doesn't work

### ISSUE THREAD

**Issue by ItsPops** [ExtendLord/DeezLoader-Reborn#98]
Hello !
Just downloaded the 3.0.3 version and auto login doesn't work.
It keeps saying "Logging in" and nothing else can be done except by deleting %USERPROFILE%\AppData\Roaming\Deezloader\autologin and by connecting manually next time to Deezloader.

Anyway that's not a huge issue and thanks a lot for giving a second life to this great piece of software.

**Comment by ExtendLord** [comment]
Do you still have those issues?
Did you waited enough time?

**Comment by ItsPops** [comment]
Hello !
It’s surprisingly working on the Mac version but not on the Windows version. 
It’s instant logging in on Mac but it never works on Windows. 
Also I noticed that the saving folder and the HiFi settings are not saving properly. 
I may try on another Windows machine if you want.

**Comment by ExtendLord** [comment]
> Also I noticed that the saving folder and the HiFi settings are not saving properly.

What do you mean?
Can you try to delete DeezLoader folder from musics folder, from %appdata% and try again in windows?

**Comment by ItsPops** [comment]
I mean that if I set in settings the downlod folder and the « enable HiFi » option on and then I close the app, settings will bel ost when I reopen it.
I tried to delete the Deezloader folder in %appdata% but this issue is still present.

Also the logging in that never passes on issue is still present.



 

De : Osher H [mailto:notifications@github.com] 
Envoyé : lundi 22 janvier 2018 17:52
À : ExtendLord/DeezLoader-Reborn <DeezLoader-Reborn@noreply.github.com>
Cc : ItsPops <brille.francois@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [ExtendLord/DeezLoader-Reborn] Auto login doesn't work (#98)

 

Also I noticed that the saving folder and the HiFi settings are not saving properly.

What do you mean?
Can you try to delete DeezLoader folder from musics folder, from %appdata% and try again in windows?
