### ISSUE TITLE
Cover Fix

### ISSUE THREAD

**Issue by gmata11** [ExtendLord/DeezLoader-Reborn#99]
Hi @ExtendLord ,
Could you add the cover on the mp3 file on your next release?
thanks!

**Comment by GoelBiju** [comment]
@gmata11, the cover file should be written to the mp3 file with the metadata automatically. I can see the cover when playing mp3 files on the computer. However when playing on other files it is not displayed, where do you not see it?

**Comment by ExtendLord** [comment]
There is a cover on mp3 files :|
![image](https://user-images.githubusercontent.com/26222159/35225668-9c35c200-ff91-11e7-8ed7-308294e148e1.png)

**Comment by gmata11** [comment]
@ExtendLord not works for me. I use Manjaro. Version 3.0.3.
![image](https://user-images.githubusercontent.com/25740908/35248070-0324db46-ffcd-11e7-8dc5-df5b7d7a492c.png)

**Comment by gmata11** [comment]
Please can you tell me if I have something wrong or if just happens on linux version. Thanks!

**Comment by auanasgheps** [comment]
Hi @gmata11 please this 
- Get yourself a MP3 tag editor application. I would recommend https://picard.musicbrainz.org/
- Import an MP3 downloaded from Deezloader. You should see a cover art. Extract the cover art as JPEG picture. In Musicbrainz you can double click the picture, it will be opened with your default picture viewer, save it.
- Save the picture as JPEG baseline. Use this website https://www.imgonline.com.ua/eng/convert.php and select _Standard JPEG_
- Delete the old cover from the MP3 and save the one you just downloaded from this website. Save changes in Musicbrainz.

Does it fix the issue?
